// Shared AI command execution — local parser first (deterministic), optional provider enhancement
import { useEditor } from '../lib/store'
import { kvGet } from '../lib/db'
import { parseCommand } from './parser'
import { planWithProvider, validatePlan, type AIConfig, DEFAULT_AI } from './provider'
import { applyPlan } from '../engine/editEngine'
import type { EditPlan } from '../lib/types'
import { uid } from '../lib/utils'

export async function runAICommand(rawText: string) {
  const text = rawText.trim()
  if (!text) return
  const s = useEditor.getState()
  const p = s.project
  if (!p) return
  const { t } = { t: (k: string) => k } // messages below are English (engine log language)
  void t

  s.addChat({ id: uid('m'), role: 'user', text, at: Date.now() })
  const thinkId = uid('m')
  s.addChat({ id: thinkId, role: 'assistant', text: 'Analyzing your timeline…', at: Date.now() })

  // built-in: undo / redo
  if (/^(undo|revert|برگردان|واگرد|برگردون)\.?$/i.test(text)) {
    s.undo()
    s.patchChat(thinkId, { text: 'Reverted the last change on the timeline.', ops: ['undo'] })
    return
  }
  if (/^(redo|ازنو|دوباره)\.?$/i.test(text)) {
    s.redo()
    s.patchChat(thinkId, { text: 'Redone.', ops: ['redo'] })
    return
  }

  const hasImages = s.assets.some((a) => a.type === 'image')
  const hasVideos = s.assets.some((a) => a.type === 'video')
  const hasMusic = s.assets.some((a) => a.type === 'audio')
  const ctx = { hasImages, hasVideos, hasMusic, bpm: p.beatMap?.bpm, duration: p.duration }

  let plan: EditPlan | null = null
  let source: 'local' | 'provider' = 'local'
  let providerNote = ''

  // 1) optional provider
  const cfg = (await kvGet<AIConfig>('aiConfig')) ?? DEFAULT_AI
  if (cfg.enabled && cfg.apiKey && cfg.baseUrl) {
    try {
      const projectContext = JSON.stringify({ duration: p.duration, aspect: p.aspect, hasImages, hasVideos, hasMusic, bpm: p.beatMap?.bpm ?? null, clips: p.tracks.reduce((n, tr) => n + tr.clips.length, 0) })
      plan = await planWithProvider(cfg, text, projectContext)
      source = 'provider'
    } catch (e) {
      providerNote = `Provider unavailable (${e instanceof Error ? e.message : 'error'}) — used the local engine instead.`
    }
  }

  // 2) local deterministic parser
  if (!plan) {
    const res = parseCommand(text, ctx)
    plan = res?.plan ?? null
  }

  if (!plan) {
    s.patchChat(thinkId, {
      role: 'assistant',
      text: "I couldn't map that to a concrete editing operation — and I never pretend to work when I don't. Try commands like:\n• “Make a 15 second cinematic football edit with beat sync”\n• “Make it darker and add dramatic zooms”\n• “Sync the cuts to the beat”\n• “Keep only the best 20 seconds”\n• “Add bold captions \"STAR EDIT\"”",
      error: true,
      at: Date.now(),
    })
    return
  }

  // 3) apply for real (with undo snapshot)
  let log: string[] = []
  let error: string | undefined
  await new Promise<void>((resolve) => {
    useEditor.getState().mutate((draft) => {
      const r = applyPlan(draft, plan!, { assets: s.assets, selection: s.selection, time: s.time })
      log = r.log
      error = r.error
    })
    resolve()
  })

  if (error) {
    s.patchChat(thinkId, { text: error, error: true, at: Date.now() })
    // roll back the empty snapshot
    s.undo()
    // remove the redo entry the undo created (nothing changed)
    useEditor.setState({ future: [] })
    return
  }

  // version snapshot
  const summaryLabel = plan.actions[0]?.type?.replace(/([A-Z])/g, ' $1').toLowerCase() ?? 'edit'
  s.addVersion(`AI: ${summaryLabel}`.slice(0, 40))

  // re-render a still frame so preview updates immediately
  const st = useEditor.getState()
  st.setTime(Math.min(st.time, st.project?.duration ?? 0))

  let header = source === 'provider' ? 'Done — plan generated by your AI provider and applied for real:' : 'Done — applied to your timeline for real:'
  if (providerNote) header += `\n${providerNote}`
  s.patchChat(thinkId, { text: header, ops: log, source, at: Date.now() })
}

// helper used by the parser bypass path in validatePlan re-export
export { validatePlan }
