// Shared AI command execution — local parser first (deterministic), optional provider enhancement
// v1.2: async lyric transcription flow with live progress + honest fallback messaging
import { useEditor } from '../lib/store'
import { kvGet } from '../lib/db'
import { parseCommand } from './parser'
import { planWithProvider, validatePlan, type AIConfig, DEFAULT_AI } from './provider'
import { applyPlan, applyLyricCaptions } from '../engine/editEngine'
import type { EditPlan } from '../lib/types'
import { uid } from '../lib/utils'
import { transcribeLyrics } from '../engine/lyrics'

export async function runAICommand(rawText: string) {
  const text = rawText.trim()
  if (!text) return
  const s = useEditor.getState()
  const p = s.project
  if (!p) return

  s.addChat({ id: uid('m'), role: 'user', text, at: Date.now() })
  const thinkId = uid('m')
  s.addChat({ id: thinkId, role: 'assistant', text: 'Analyzing your timeline…', at: Date.now() })

  // built-in: undo / redo
  if (/^(undo|revert|برگردان|واگرد|برگردون)\.?$/i.test(text)) {
    s.undo()
    s.patchChat(thinkId, { text: 'Reverted the last change on the timeline.', ops: ['undo'] })
    return
  }
  if (/^(redo|ازنو|دوباره)\.?$/i.test(text)) {
    s.redo()
    s.patchChat(thinkId, { text: 'Redone.', ops: ['redo'] })
    return
  }

  const hasImages = s.assets.some((a) => a.type === 'image')
  const hasVideos = s.assets.some((a) => a.type === 'video')
  const hasMusic = s.assets.some((a) => a.type === 'audio')
  const clips = p.tracks.reduce((n, tr) => n + tr.clips.length, 0)
  const ctx = { hasImages, hasVideos, hasMusic, bpm: p.beatMap?.bpm, duration: p.duration, clips }

  let plan: EditPlan | null = null
  let source: 'local' | 'provider' = 'local'
  let providerNote = ''
  let fallback = false

  // 1) optional provider
  const cfg = (await kvGet<AIConfig>('aiConfig')) ?? DEFAULT_AI
  if (cfg.enabled && cfg.apiKey && cfg.baseUrl) {
    try {
      const projectContext = JSON.stringify({ duration: p.duration, aspect: p.aspect, hasImages, hasVideos, hasMusic, bpm: p.beatMap?.bpm ?? null, clips })
      plan = await planWithProvider(cfg, text, projectContext)
      source = 'provider'
    } catch (e) {
      providerNote = `Provider unavailable (${e instanceof Error ? e.message : 'error'}) — used the local engine instead.`
    }
  }

  // 2) local deterministic parser
  if (!plan) {
    const res = parseCommand(text, ctx)
    if (res) {
      plan = res.plan
      fallback = !!res.fallback
    }
  }

  if (!plan) {
    const noMedia = !hasImages && !hasVideos && clips === 0
    s.patchChat(thinkId, {
      role: 'assistant',
      text: noMedia
        ? 'There is nothing on the timeline yet. Upload photos, videos or music in the Media panel first — then tell me what to build, e.g. “Make a 15 second cinematic edit with beat sync”.'
        : 'I read that as a chat message rather than an editing command. Real things I can do right now:\n• “Make a 15 second cinematic football edit with beat sync”\n• “Match the music to my video”\n• “Convert the song to text” (real lyric transcription)\n• “Convert to TikTok format” (smart reframe)\n• “Add a title \"GOAL\" with font Anton”\n• “Add a speed ramp” / “Add cinematic bars” / “Add an outro”',
      error: false,
      at: Date.now(),
    })
    return
  }

  // 3) lyric transcription — async with live progress
  const lyricsAction = plan.actions.find((a): a is Extract<typeof a, { type: 'autoLyrics' }> => a.type === 'autoLyrics')
  if (lyricsAction) {
    const other = plan.actions.filter((a) => a.type !== 'autoLyrics')
    if (other.length) {
      await new Promise<void>((resolve) => {
        useEditor.getState().mutate((draft) => {
          applyPlan(draft, { actions: other }, { assets: s.assets, selection: s.selection, time: s.time })
        })
        resolve()
      })
    }
    await runAutoLyricsFlow(thinkId, lyricsAction.quality ?? 'fast')
    return
  }

  // 4) apply for real (with undo snapshot)
  let log: string[] = []
  let error: string | undefined
  await new Promise<void>((resolve) => {
    useEditor.getState().mutate((draft) => {
      const r = applyPlan(draft, plan!, { assets: s.assets, selection: s.selection, time: s.time })
      log = r.log
      error = r.error
    })
    resolve()
  })

  if (error) {
    s.patchChat(thinkId, { text: error, error: true, at: Date.now() })
    // roll back the empty snapshot
    s.undo()
    // remove the redo entry the undo created (nothing changed)
    useEditor.setState({ future: [] })
    return
  }

  // version snapshot
  const summaryLabel = plan.actions[0]?.type?.replace(/([A-Z])/g, ' $1').toLowerCase() ?? 'edit'
  s.addVersion(`AI: ${summaryLabel}`.slice(0, 40))

  // re-render a still frame so preview updates immediately
  const st = useEditor.getState()
  st.setTime(Math.min(st.time, st.project?.duration ?? 0))

  let header = source === 'provider' ? 'Done — plan generated by your AI provider and applied for real:' : 'Done — applied to your timeline for real:'
  if (fallback) header = 'Done — I read your request as a professional polish pass and applied it for real (undo is available if you meant something else):'
  if (providerNote) header += `\n${providerNote}`
  s.patchChat(thinkId, { text: header, ops: log, source, at: Date.now() })
}

/** Real lyric transcription with honest progress updates in the chat. */
export async function runAutoLyricsFlow(chatId?: string, quality: 'fast' | 'best' = 'fast', mediaId?: string) {
  const s = useEditor.getState()
  const p = s.project
  // same selection rule as the rest of the app: the analyzed track wins, else the first
  const music = (mediaId ? s.assets.find((a) => a.type === 'audio' && a.id === mediaId) : undefined)
    ?? s.assets.find((a) => a.type === 'audio' && a.id === p?.beatMap?.mediaId)
    ?? s.assets.find((a) => a.type === 'audio')
  const blob = music ? s.blobs.get(music.id) : undefined
  const id = chatId ?? uid('m')

  if (!music || !blob) {
    s.addChat({
      id, role: 'assistant', at: Date.now(),
      text: 'Lyric transcription needs music. Upload an MP3/WAV in the Media panel first, then ask again.',
      error: true,
    })
    return
  }
  const trackName = music.name?.length ? ` (“${music.name}”)` : ''

  // start a real chat entry so progress updates have something to patch
  s.addChat({ id, role: 'assistant', text: `Transcribing vocals from ${trackName || 'your track'} — the Whisper model loads first (downloaded once, then cached)…`, at: Date.now() })
  try {
    const lines = await transcribeLyrics(
      blob,
      { quality },
      (pr) => {
        const pct = Math.round(pr.pct * 100)
        if (pr.stage === 'loading') {
          s.patchChat(id, { text: `Loading the Whisper model — ${pct}% (downloaded once, then cached locally)…` })
        } else {
          s.patchChat(id, { text: `Transcribing vocals… this runs fully on your device and can take 30–90s for a typical song.` })
        }
      }
    )
    let log: string[] = []
    useEditor.getState().mutate((draft) => {
      log = applyLyricCaptions(draft, lines, 'karaoke')
    })
    s.addVersion('AI: lyric captions')
    const st = useEditor.getState()
    st.setTime(Math.min(st.time, st.project?.duration ?? 0))
    const coverage = lines.length ? `${lines[0].start.toFixed(1)}s → ${lines[lines.length - 1].end.toFixed(1)}s` : ''
    s.patchChat(id, {
      text: `Done — real vocal transcription, applied as synced karaoke captions (${coverage}):`,
      ops: [...log, `Detected language handling: auto · lines: ${lines.length}`],
    })
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'Transcription failed'
    s.patchChat(id, {
      text: `I could not produce lyrics honestly: ${msg}\nTips: songs with clear vocals work best — heavy instrumental mixes are harder. “Best quality” mode uses a larger model.`,
      error: true,
    })
  }
}

// helper used by the parser bypass path in validatePlan re-export
export { validatePlan }
